ASC-993 linter not respecting valid python styling
rcbops/flake8-pytest-mark pull request #27
Opened 2018-11-26 21:07 UTC by mwbutcher

Prior to this change, marks without parens were being
ignored.

This Commit adds logic in rules.py to diferentiate
between ast.Call and ast.Attribute and adds a couple
tests around this issue.

2018-11-28 16:15 UTC, zreichert requested changes
I think this behavior is not quite right.  In the example I commented on if we decorated a test with
`@pytest.mark.jira()`
It would fail our xml schema validation.

2018-11-28 16:15 UTC, zreichert commented on tests/test_multi_value_mark.py
> +    assert result.out_lines == []
I think this test should fail but I am not sure.  Since this mark implements a `value_regex` should it check to see if the values match the regex?

`pytest_mark1 = name=jira,value_regex=[a-zA-Z]*-\d*,allow_multiple_args=true`

I guess the question is 'Is an empty value acceptable, when you have defined a match or regex?'

2018-12-03 23:00 UTC, zreichert commented on flake8_pytest_mark/rules.py
> +        if isinstance(decorator, ast.Attribute):
Could this be `elif isinstance(decorator, ast.Attribute):`?

2018-12-03 23:17 UTC, mwbutcher commented on flake8_pytest_mark/rules.py
> +        if isinstance(decorator, ast.Attribute):
Yeah, those are mutually exclusive

2018-12-03 23:29 UTC, zreichert approved these changes

2018-12-04 22:22 UTC, merged